# Generated by Django 2.2.16 on 2020-12-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201230_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emailAddress',
            field=models.EmailField(blank=True, max_length=250),
        ),
    ]
