# Generated by Django 2.2.16 on 2021-01-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210104_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='emailAddress',
            field=models.EmailField(max_length=250),
        ),
    ]
