# Generated by Django 2.2.16 on 2021-01-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
    ]
